# Generated by Django 4.2.5 on 2023-09-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='country',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
